"""
gRPC transport for high-performance event ingestion.

Uses binary protobuf + HTTP/2 to achieve 30-50% overhead reduction
compared to REST/JSON for high-frequency /track operations.
"""
from __future__ import annotations

import os
from typing import Optional

import grpc

# These will be generated by grpcio-tools from the proto file shipped in ./protos/
# Run: python -m grpc_tools.protoc -I./protos --python_out=./src/nullrun/v1 --grpc_python_out=./src/nullrun/v1 ./protos/nullrun/v1/track.proto
try:
    from nullrun.v1 import track_pb2, track_pb2_grpc
except ImportError:
    # Proto files not generated yet
    track_pb2 = None
    track_pb2_grpc = None


class GrpcTransport:
    """
    High-performance gRPC transport for event ingestion.

    Usage:
        transport = GrpcTransport(
            api_url="localhost:50051",
            api_key="your-api-key"
        )
        result = transport.batch_track([...])
    """

    def __init__(
        self,
        api_url: str,
        api_key: str,
        use_tls: bool = True,
    ):
        """
        Initialize gRPC transport.

        Args:
            api_url: gRPC server address (e.g., "localhost:50051")
            api_key: API key for authentication
            use_tls: Whether to use TLS (default True in production)
        """
        self.api_url = api_url
        self.api_key = api_key
        self.use_tls = use_tls

        if track_pb2 is None or track_pb2_grpc is None:
            raise RuntimeError(
                "Proto files not generated. Run:\n"
                "make protos   # from the SDK repo root"
            )

        # Create channel with optional TLS
        if use_tls:
            # In production, configure proper TLS credentials
            credentials = grpc.ssl_channel_credentials()
            self.channel = grpc.secure_channel(api_url, credentials)
        else:
            self.channel = grpc.insecure_channel(api_url)

        self.stub = track_pb2_grpc.TrackServiceStub(self.channel)

    def _make_metadata(self) -> list[tuple[str, str]]:
        """Create gRPC metadata with auth headers."""
        return [
            ("x-api-key", self.api_key),
        ]

    def track(
        self,
        event_id: str,
        workflow_id: str,
        tokens: int,
        cost_cents: int,
        tool_name: Optional[str] = None,
        is_retry: bool = False,
        event_type: str = "",
    ) -> tuple[bool, str]:
        """
        Track a single event via gRPC.

        Returns:
            Tuple of (accepted, message)
        """
        request = track_pb2.TrackRequest(
            event_id=event_id,
            workflow_id=workflow_id,
            event_type=event_type,
            tokens=tokens,
            cost_cents=cost_cents,
            tool_name=tool_name or "",
            is_retry=is_retry,
        )

        try:
            response = self.stub.Track(request, metadata=self._make_metadata())
            return response.accepted, response.message
        except grpc.RpcError as e:
            return False, f"gRPC error: {e.code()}: {e.details()}"

    def batch_track(
        self,
        events: list[dict],
    ) -> dict:
        """
        Track multiple events via gRPC batch API.

        Args:
            events: List of event dicts with keys:
                - event_id: str
                - workflow_id: str
                - tokens: int
                - cost_cents: int
                - tool_name: Optional[str]
                - is_retry: bool
                - event_type: str (optional)

        Returns:
            Dict with:
                - accepted_event_ids: List[str]
                - actions_taken: List[dict]
        """
        proto_events = []
        for event in events:
            proto_events.append(track_pb2.TrackRequest(
                event_id=event["event_id"],
                workflow_id=event["workflow_id"],
                event_type=event.get("event_type", ""),
                tokens=event["tokens"],
                cost_cents=event["cost_cents"],
                tool_name=event.get("tool_name", "") or "",
                is_retry=event.get("is_retry", False),
            ))

        request = track_pb2.BatchTrackRequest(events=proto_events)

        try:
            response = self.stub.BatchTrack(request, metadata=self._make_metadata())
            return {
                "accepted_event_ids": list(response.accepted_event_ids),
                "actions_taken": [
                    {"type": a.type, "workflow_id": a.workflow_id, "reason": a.reason}
                    for a in response.actions_taken
                ],
            }
        except grpc.RpcError as e:
            return {
                "accepted_event_ids": [],
                "actions_taken": [],
                "error": f"gRPC error: {e.code()}: {e.details()}",
            }

    def close(self):
        """Close the gRPC channel."""
        if hasattr(self, "channel"):
            self.channel.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
        return False


def create_grpc_transport(
    api_url: Optional[str] = None,
    api_key: Optional[str] = None,
) -> Optional[GrpcTransport]:
    """
    Factory function to create GrpcTransport if gRPC is available.

    Returns None if:
    - NULLRUN_USE_GRPC env var is not set
    - Required proto files are not generated
    """
    if not os.getenv("NULLRUN_USE_GRPC"):
        return None

    url = api_url or os.getenv("NULLRUN_GRPC_URL", "localhost:50051")
    key = api_key or os.getenv("NULLRUN_API_KEY", "")

    if not key:
        return None

    try:
        return GrpcTransport(api_url=url, api_key=key)
    except RuntimeError:
        # Proto files not generated
        return None